apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: agent
  name: agent
  namespace: gleam
spec:
  replicas: 3
  selector:
    matchLabels:
      service: agent
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: agent
    spec:
      containers:
      - name: agent
        image: eisokant/gleam
        resources:
          limits:
            memory: "1048Mi"
            cpu: "0.6"
        args:
          - "agent"
          - "--memory=1048 --master=master:45326"
        volumeMounts:
        - name: gleam-data
          mountPath: /data
      volumes:
        - name: gleam-data
          persistentVolumeClaim:
            claimName: gleam-pvc
            readOnly: true
